/**
 * ArtifactPreview — HTML preview panel with iframe
 * ==================================================
 * Loads file contents and renders in a sandboxed iframe.
 * Used for previewing HTML/React artifacts generated by the AI.
 */
// @ts-nocheck


import React, { useCallback, useEffect } from 'react';
import { useEditorStore } from '../../stores/editorStore';

const ArtifactPreview: React.FC = () => {
  const { previewVisible, previewTitle, previewContent, hidePreview } = useEditorStore();

  const handleClose = useCallback(() => {
    hidePreview();
  }, [hidePreview]);

  // Expose previewArtifact globally for formatContent buttons
  useEffect(() => {
    const original = (window as any).previewArtifact;
    (window as any).previewArtifact = async (filePath: string, fileName: string) => {
      try {
        const res = await fetch(`/api/fs/read?file=${encodeURIComponent(filePath)}`);
        const data = await res.json();
        if (data.content) {
          useEditorStore.getState().showPreview(filePath, fileName, data.content);
        } else {
          useEditorStore.getState().showPreview(
            filePath,
            `Error: ${fileName}`,
            `<h3>Error loading preview</h3><p>${data.error || 'Unknown error'}</p>`
          );
        }
      } catch (err: any) {
        useEditorStore.getState().showPreview(
          filePath,
          `Error: ${fileName}`,
          `<h3>Error fetching preview</h3><p>${err.message}</p>`
        );
      }
    };
    return () => {
      (window as any).previewArtifact = original;
    };
  }, []);

  if (!previewVisible) return null;

  return (
    <div
      className="ide-preview glass-panel"
      style={{
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
        background: '#ffffff',
        flex: 1,
      }}
    >
      {/* Preview Header */}
      <div
        className="preview-tabs"
        style={{
          display: 'flex',
          background: '#f0f0f0',
          borderBottom: '1px solid #ccc',
          justifyContent: 'space-between',
          alignItems: 'center',
          paddingRight: 8,
        }}
      >
        <div
          className="preview-tab active"
          style={{
            padding: '10px 16px',
            background: '#fff',
            color: '#333',
            fontSize: 13,
            fontWeight: 'bold',
            display: 'flex',
            alignItems: 'center',
            borderTop: '1px solid #007acc',
            cursor: 'pointer',
          }}
        >
          <span id="preview-title">{previewTitle}</span>
        </div>
        <button
          id="close-preview-btn"
          className="icon-btn"
          style={{ color: '#666' }}
          onClick={handleClose}
        >
          ✕
        </button>
      </div>

      {/* Preview Iframe */}
      <div style={{ flex: 1, position: 'relative' }}>
        <iframe
          id="preview-iframe"
          title="Artifact Preview"
          srcDoc={previewContent}
          style={{
            width: '100%',
            height: '100%',
            border: 'none',
            background: '#fff',
          }}
          sandbox="allow-scripts allow-forms allow-popups"
        />
      </div>
    </div>
  );
};

export default ArtifactPreview;
